[package]
name = "brocolib"
version = "0.1.0"
authors = ["StackDoubleFlow <ojaslandge@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "2"
binde = { git = "https://github.com/StackDoubleFlow/binde" }
bad64 = { version = "0.12", optional = true }
byteorder = "1.4"
object = "0.38"
binread = "2.2"
libloading = "0.9"

iced-x86 = { version = "1.21", optional = true }

[features]
default = ["elf", "pe", "elf_aarch64", "pe_x64", "il2cpp_v31"]
elf = ["object/elf"]
pe = ["object/pe"]

# Target-specific features e.g xrefs
elf_aarch64 = ["elf", "dep:bad64"]
pe_x64 = ["pe", "dep:iced-x86"]

# IL2CPP Version-specific features
il2cpp_v31 = []
