[package]
name = "brocolib"
version = "0.1.0"
authors = ["StackDoubleFlow <ojaslandge@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "2"
binde = { git = "https://github.com/StackDoubleFlow/binde" }
bad64 = { version = "0.12", optional = true }
byteorder = "1.5"
binread = "2.2"
iced-x86 = { version = "1.21", optional = true }

[dependencies.object]
version = "0.39"
default-features = false
features = ["read_core"]

[features]
default = ["elf", "pe", "aarch64", "x86_64"]
elf = ["object/elf"]
pe = ["object/pe"]

# Target-specific features e.g xrefs
aarch64 = ["dep:bad64"]
x86_64 = ["dep:iced-x86"]

# IL2CPP Version-specific features. Exactly one must be enabled.
il2cpp_v31 = []
il2cpp_v39 = []

[dev-dependencies]
anyhow = "1.0"
